import Image from "next/image";
import { sourceUrl } from "@/data/projects";
export default function ProjectVisual({ slug }: { slug: string }) {
  if (slug === "autonomous-driving-edge-perception") {
    return (
      <aside className="example-note">
        <p className="eyebrow">Delivered demonstration</p>
        <h2>Detection, tracking, and lane perception in one pipeline.</h2>
        <p>
          This silent demo is an annotated output generated by the delivered
          system from a public Udacity road clip. It shows detected vehicles,
          persistent track IDs, the lane and drivable-area overlay, and the live
          performance HUD.
        </p>
        <figure className="mt-6">
          <video
            className="w-full h-auto rounded-lg border border-line bg-ink"
            controls
            playsInline
            preload="metadata"
            poster="/projects/autonomous-driving/road-perception-poster.webp"
            aria-label="Autonomous-driving perception system demonstration"
          >
            <source
              src="/projects/autonomous-driving/road-perception-demo.mp4"
              type="video/mp4"
            />
            Your browser does not support the embedded demonstration video.
          </video>
          <figcaption className="font-mono text-xs text-ink-soft mt-3">
            8.8-second H.264 demo · public road footage · no audio
          </figcaption>
        </figure>
        <dl className="grid grid-cols-3 max-[700px]:grid-cols-1 gap-4 mt-7">
          <div>
            <dt className="font-mono text-xs uppercase text-clay-deep">
              Processing rate
            </dt>
            <dd className="font-serif text-2xl mt-1">9.42-9.58 FPS</dd>
          </div>
          <div>
            <dt className="font-mono text-xs uppercase text-clay-deep">
              Mean inference
            </dt>
            <dd className="font-serif text-2xl mt-1">91.63-92.30 ms</dd>
          </div>
          <div>
            <dt className="font-mono text-xs uppercase text-clay-deep">
              Test environment
            </dt>
            <dd className="font-serif text-2xl mt-1">1 logical CPU</dd>
          </div>
        </dl>
      </aside>
    );
  }
  if (slug === "local-document-deid") {
    return (
      <aside className="example-note">
        <p className="eyebrow">Review workflow</p>
        <h2>Local review before approved export.</h2>
        <p>
          The demo pack uses synthetic files to show the privacy workflow: local
          upload, extracted source text, human review, manual correction, and
          approved DOCX export. These screenshots do not contain client data.
        </p>
        <div className="grid grid-cols-2 max-[600px]:grid-cols-1 gap-5 mt-6">
          {[
            {
              src: "local-application.png",
              alt: "Local De-ID application running in a browser",
              caption: "Local application",
            },
            {
              src: "extracted-source.png",
              alt: "Extracted source text preview for review",
              caption: "Extracted source",
            },
            {
              src: "human-review.png",
              alt: "Human review screen with redaction decisions",
              caption: "Human review",
            },
            {
              src: "approved-export.png",
              alt: "Approved export screen after review attestation",
              caption: "Approved export",
            },
          ].map((item) => (
            <figure key={item.src}>
              <Image
                src={`/projects/local-deid/${item.src}`}
                alt={item.alt}
                width={624}
                height={544}
                sizes="(max-width:600px) 85vw, 420px"
                className="rounded-lg w-full h-auto border border-line"
              />
              <figcaption className="font-mono text-xs text-ink-soft mt-3">
                {item.caption}
              </figcaption>
            </figure>
          ))}
        </div>
      </aside>
    );
  }
  if (slug !== "automated-color-grading") return null;
  return (
    <aside className="example-note">
      <p className="eyebrow">From the repository</p>
      <h2>A real color-transfer example.</h2>
      <p>
        The committed example transfers a warmer reference look to an overcast
        city scene. These images are resized copies of the original target and
        saved output.
      </p>
      <div className="grid grid-cols-2 max-[600px]:grid-cols-1 gap-5 mt-6">
        {[
          {
            src: "color-target.webp",
            alt: "Original city street with cool gray tones and an overcast sky",
            caption: "Original target",
          },
          {
            src: "color-output.webp",
            alt: "The same city street after color transfer, with warm amber tones",
            caption: "Processed output",
          },
        ].map((item) => (
          <figure key={item.src}>
            <Image
              src={`/projects/${item.src}`}
              alt={item.alt}
              width={960}
              height={640}
              sizes="(max-width:600px) 85vw, 420px"
              className="rounded-lg w-full h-auto"
            />
            <figcaption className="font-mono text-xs text-ink-soft mt-3">
              {item.caption}
            </figcaption>
          </figure>
        ))}
      </div>
      <div className="flex flex-wrap gap-5 mt-6">
        <a
          className="text-link"
          href={sourceUrl("automated-color-grading", "reference_sunset.jpg")}
        >
          Reference image ↗
        </a>
        <a
          className="text-link"
          href={sourceUrl("automated-color-grading", "target_city.jpg")}
        >
          Original target source ↗
        </a>
        <a
          className="text-link"
          href={sourceUrl(
            "automated-color-grading",
            "output/processed_target_city.jpg",
          )}
        >
          Processed output source ↗
        </a>
      </div>
    </aside>
  );
}
